service-url: /api/user-service
out-service:
  asset:
    url: http://localhost:7979

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8084
  shutdown: graceful

spring:
  application:
    name: user-application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/user-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true

  kafka:
    producer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

  data:
    redis:
      host: localhost
      password: dkssudgktpdy
      port: 6379

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.pda

eureka:
  instance:
    hostname:
    healthCheckUrlPath: /actuator/health
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    eureka-server-port: 8761
    register-with-eureka: true
    fetch-registry: true
    disable-delta: true
    service-url:
      defaultZone: http://192.168.2.20:8761/eureka

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown, health
