service-url: /api/user-service
out-service:
  asset:
    url: http://localhost:7979

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8084

spring:
  application:
    name: user-application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/user-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true

  kafka:
    producer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

  data:
    redis:
      host: localhost
      password: dkssudgktpdy
      port: 6379

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.pda