service-url: /api/board-service

server:
  port: 8082

spring:
  config:
    import: "application-keys.yml"
  application:
    name: board-application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.pda
  use-fqn: true