service-url: /api/product-service
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  port: 8083
  shutdown: graceful

spring:
  application:
    name: product-application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3344/product_db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.pda

eureka:
  instance:
    healthCheckUrlPath: /actuator/health
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    eureka-server-port: 8761
    register-with-eureka: true
    fetch-registry: true
    disable-delta: true
    service-url:
      defaultZone: http://192.168.2.20:8761/eureka

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown, health