version: '3'
services:
  mysql:
    container_name: user-db
    image: mysql:8.0.33-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user-db
      - TZ="Asia/Seoul"
    ports:
      - "3310:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    stdin_open: true # `-i`
    tty: true # `-t`

  redis:
    image: redis:latest
    container_name: refresh-redis
    ports:
      - "6379:6379"
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./conf/redis.conf:/usr/local/conf/redis.conf