service-url: /api

server:
  port: 8080
  servlet:
    context-path: ${service-url}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:5173'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path= ${service-url}/user-service/**
          filters:
            - RewritePath=${service-url}/user-service/(?<path>.*),/$\{path}
        - id: challenge-service
          uri: http://localhost:8081
          predicates:
            - Path= ${service-url}/challenge-service/**
          filters:
            - RewritePath=${service-url}/challenge-service/(?<path>.*),/$\{path}
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path= ${service-url}/product-service/**
          filters:
            - RewritePath=${service-url}/product-service/(?<path>.*),/$\{path}
        - id: board-service
          uri: http://localhost:8082
          predicates:
            - Path= ${service-url}/board-service/**
          filters:
            - RewritePath=${service-url}/board-service/(?<path>.*),/$\{path}
        - id: credit-service
          uri: http://localhost:8085
          predicates:
            - Path= ${service-url}/credit-service/**
          filters:
            - RewritePath=${service-url}/credit-service/(?<path>.*),/$\{path}
        - id: alert-service
          uri: http://localhost:8089
          predicates:
            - Path= ${service-url}/alert-service/**
          filters:
            - RewritePath=${service-url}/alert-service/(?<path>.*),/$\{path}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
#  api-docs:
#    path: /api/v3/api-docs
  webjars:
    prefix: ${service-url}
  swagger-ui:
    operations-sorter: alpha
    use-root-path: true
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: ${service-url}/user-service/v3/api-docs
        name: User Service
      - url: ${service-url}/challenge-service/v3/api-docs
        name: Challenge Service
      - url: ${service-url}/product-service/v3/api-docs
        name: Product Service
      - url: ${service-url}/board-service/v3/api-docs
        name: Board Service
      - url: ${service-url}/alert-service/v3/api-docs
        name: Alert Service
      - url: ${service-url}/credit-service/v3/api-docs
        name: Credit Service

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    registry-fetch-interval-seconds: 3
#    disable-delta: true
#    service-url:
#      defaultZone: http://192.168.2.20:8761/eureka

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE