server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  server:
    eviction-interval-time-in-ms: 10000
    response-cache-update-interval-ms: 1000
    enable-self-preservation: false
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: false
    fetch-registry: false