service-url: /api/alert-service

logging:
  level:
    org:
      hibernate:
        SQL: debug

server:
  port: 8089

spring:
  application:
    name: alert-application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3388/alert-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

  kafka:
    consumer:
      group-id: alert-group # Group Id
      auto-offset-reset: earliest
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.pda